# syntax=docker/dockerfile:1
# Production web image (Expo static export + nginx). This repo is not Next.js.

FROM node:22-bookworm-slim AS build
WORKDIR /app
ENV CI=1
ENV EXPO_NO_TELEMETRY=1
ARG EXPO_PUBLIC_SITE_URL
ARG EXPO_PUBLIC_APP_STORE_URL
ARG EXPO_PUBLIC_PLAY_STORE_URL
ARG EXPO_PUBLIC_IOS_APP_URL
ARG EXPO_PUBLIC_ANDROID_APP_URL
ARG EXPO_PUBLIC_SUPPORT_PHONE
ARG EXPO_PUBLIC_SUPPORT_WHATSAPP
ARG EXPO_PUBLIC_SUPPORT_EMAIL
ARG EXPO_PUBLIC_ANALYTICS
ENV EXPO_PUBLIC_SITE_URL=$EXPO_PUBLIC_SITE_URL
ENV EXPO_PUBLIC_APP_STORE_URL=$EXPO_PUBLIC_APP_STORE_URL
ENV EXPO_PUBLIC_PLAY_STORE_URL=$EXPO_PUBLIC_PLAY_STORE_URL
ENV EXPO_PUBLIC_IOS_APP_URL=$EXPO_PUBLIC_IOS_APP_URL
ENV EXPO_PUBLIC_ANDROID_APP_URL=$EXPO_PUBLIC_ANDROID_APP_URL
ENV EXPO_PUBLIC_SUPPORT_PHONE=$EXPO_PUBLIC_SUPPORT_PHONE
ENV EXPO_PUBLIC_SUPPORT_WHATSAPP=$EXPO_PUBLIC_SUPPORT_WHATSAPP
ENV EXPO_PUBLIC_SUPPORT_EMAIL=$EXPO_PUBLIC_SUPPORT_EMAIL
ENV EXPO_PUBLIC_ANALYTICS=$EXPO_PUBLIC_ANALYTICS
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npx expo export --platform web --output-dir dist

FROM nginx:1.27-alpine
COPY deploy/nginx.staging.conf /etc/nginx/conf.d/default.conf
RUN sed -i 's/listen 80;/listen 3000;/' /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3000
HEALTHCHECK --interval=15s --timeout=5s --start-period=10s --retries=5 \
  CMD wget -qO- http://127.0.0.1:3000/ >/dev/null || exit 1
