export const copy = {
  appName: 'Транспортні послуги',
  authTitle: 'Потрібна допомога на дорозі?',
  authSubtitle:
    'Евакуатор, переїзд, вантаж або техдопомога. Замовлення за кілька кроків.',
  continueAsCustomer: 'Продовжити як клієнт',
  phonePlaceholder: '+380',
  otpPlaceholder: 'Код',
  requestCode: 'Отримати код',
  verifyCode: 'Увійти',
  resendCode: 'Надіслати код ще раз',
  authError: 'Не вдалося увійти',
  customerHomeTitle: 'Яка послуга потрібна?',
  customerHomeSubtitle: 'Евакуатор — найшвидший шлях, якщо авто вже не їде.',
  serviceTow: 'Евакуатор',
  serviceTowHint: 'Терміново забрати авто',
  serviceMoving: 'Переїзд',
  serviceMovingHint: 'Квартира, офіс, речі',
  serviceCargo: 'Вантажні перевезення',
  serviceCargoHint: 'Доставка вантажу',
  serviceRoadside: 'Допомога на дорозі',
  serviceRoadsideHint: 'Запуск, колесо, паливо',
  switchToDriver: 'Режим водія',
  switchToCustomer: 'Режим клієнта',
  signOut: 'Вийти',
  driverHomeTitle: 'Режим водія',
  driverOnline: 'На лінії',
  driverOffline: 'Не в мережі',
  vehicleTitle: 'Автомобіль',
  vehiclePlaceholder: 'Тип авто та доступні послуги',
  earningsTitle: 'Заробіток',
  earningsAmount: '₴ 0',
  mapTitle: 'Звідки забрати?',
  mapSubtitle: 'Оберіть точку на мапі або знайдіть адресу в Україні.',
  mapPickup: 'Подача',
  mapDestination: 'Куди',
  mapAddDestination: 'Додати пункт призначення',
  mapSearchPlaceholder: 'Адреса в Україні',
  mapSearch: 'Шукати',
  mapDone: 'Готово',
  useMyLocation: 'Моє місце',
  locationDenied: 'Немає доступу до геолокації',
  locationUnavailable: 'Не вдалося визначити місце',
  mapNoResults: 'Адрес не знайдено',
  mapRouteError: 'Маршрут недоступний',
  mapOutsideUkraine: 'Працюємо лише в Україні',
  myOrders: 'Мої замовлення',
  backHome: 'На головну',
  ordersEmpty: 'Поки немає замовлень',
  loading: 'Завантаження…',
  detailsTitle: 'Деталі замовлення',
  detailsSubtitle: 'Оберіть тип авто, щоб отримати ціну з сервера.',
  vehicleCar: 'Легкове',
  vehicleSuv: 'Позашляховик',
  vehicleVan: 'Мікроавтобус',
  vehicleMotorcycle: 'Мото',
  requestQuote: 'Отримати ціну',
  quoteTitle: 'Вартість',
  quoteExpires: 'Ціна дійсна до',
  confirmOrder: 'Замовити',
  orderTitle: 'Замовлення',
  orderSearching: 'Шукаємо виконавця',
  orderOffered: 'Очікуємо відповідь водія',
  orderAccepted: 'Водія знайдено',
  orderEnRoute: 'Водій їде',
  orderArrived: 'Водій на місці',
  orderInProgress: 'Виконується',
  orderCompleted: 'Виконано',
  orderCancelled: 'Скасовано',
  orderExpired: 'Час пошуку минув',
  cancelOrder: 'Скасувати замовлення',
  pickupLabel: 'Подача',
  destinationLabel: 'Куди',
  requestError: 'Не вдалося виконати запит',
  sessionExpired: 'Сесію завершено. Увійдіть знову.',
  profileTitle: 'Профіль',
  profileName: 'Імʼя',
  profileSave: 'Зберегти',
  phoneLocalHint: '9 цифр після +380',
  driverOfferTitle: 'Пропозиція',
  acceptOffer: 'Прийняти',
  rejectOffer: 'Відхилити',
  noOffers: 'Немає активних пропозицій',
  goOnlineHint: 'Увімкніть «На лінії», щоб отримувати замовлення.',
  markEnRoute: 'Виїхав',
  markArrived: 'На місці',
  markStart: 'Почати роботу',
  markComplete: 'Завершити',
  adminTitle: 'Адмін',
  adminOrders: 'Замовлення',
  adminDrivers: 'Водії',
  approveDriver: 'Підтвердити',
  suspendDriver: 'Призупинити',
  retry: 'Повторити',
  empty: 'Порожньо',
  notesPlaceholder: 'Коментар (необовʼязково)',
  orderIdLabel: 'Номер замовлення',
  driverLabel: 'Водій',
  vehiclePlate: 'Номер авто',
  saved: 'Збережено',
  adminDashboard: 'Панель',
  adminUsers: 'Користувачі',
  adminPricing: 'Тарифи',
  adminExport: 'Експорт CSV',
  switchToAdmin: 'Адмін-панель',
  ratingLabel: 'Рейтинг',
  verificationLabel: 'Верифікація',
  createdAtLabel: 'Створено',
} as const;
