export const copy = {
  appName: 'Транспортні послуги',
  authTitle: 'Потрібна допомога на дорозі?',
  authSubtitle:
    'Евакуатор, переїзд, вантаж або техдопомога. Замовлення за кілька кроків.',
  continueAsCustomer: 'Продовжити як клієнт',
  phonePlaceholder: '+380',
  otpPlaceholder: 'Код',
  requestCode: 'Отримати код',
  verifyCode: 'Увійти',
  resendCode: 'Надіслати код ще раз',
  authError: 'Не вдалося увійти',
  customerHomeTitle: 'Яка послуга потрібна?',
  customerHomeSubtitle: 'Евакуатор — найшвидший шлях, якщо авто вже не їде.',
  serviceTow: 'Евакуатор',
  serviceTowHint: 'Терміново забрати авто',
  serviceMoving: 'Переїзд',
  serviceMovingHint: 'Квартира, офіс, речі',
  serviceCargo: 'Вантажні перевезення',
  serviceCargoHint: 'Доставка вантажу',
  serviceRoadside: 'Допомога на дорозі',
  serviceRoadsideHint: 'Запуск, колесо, паливо',
  switchToDriver: 'Режим водія',
  switchToCustomer: 'Режим клієнта',
  signOut: 'Вийти',
  driverHomeTitle: 'Режим водія',
  driverOnline: 'На лінії',
  driverOffline: 'Не в мережі',
  vehicleTitle: 'Автомобіль',
  vehiclePlaceholder: 'Тип авто та доступні послуги',
  earningsTitle: 'Заробіток',
  earningsAmount: '₴ 0',
} as const;
